// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Lecteurmp3.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ceri.mahmoud.GUInterface.iceImplementation;

public interface ManagerPrx extends com.zeroc.Ice.ObjectPrx
{
    default boolean ajouterMorceau(String titre, String genre, String auteur, String adresse)
    {
        return ajouterMorceau(titre, genre, auteur, adresse, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean ajouterMorceau(String titre, String genre, String auteur, String adresse, java.util.Map<String, String> context)
    {
        return _iceI_ajouterMorceauAsync(titre, genre, auteur, adresse, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Boolean> ajouterMorceauAsync(String titre, String genre, String auteur, String adresse)
    {
        return _iceI_ajouterMorceauAsync(titre, genre, auteur, adresse, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Boolean> ajouterMorceauAsync(String titre, String genre, String auteur, String adresse, java.util.Map<String, String> context)
    {
        return _iceI_ajouterMorceauAsync(titre, genre, auteur, adresse, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Boolean> _iceI_ajouterMorceauAsync(String iceP_titre, String iceP_genre, String iceP_auteur, String iceP_adresse, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "ajouterMorceau", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_titre);
                     ostr.writeString(iceP_genre);
                     ostr.writeString(iceP_auteur);
                     ostr.writeString(iceP_adresse);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default Morceau[] rechMorceauxParArtiste(String artiste)
    {
        return rechMorceauxParArtiste(artiste, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Morceau[] rechMorceauxParArtiste(String artiste, java.util.Map<String, String> context)
    {
        return _iceI_rechMorceauxParArtisteAsync(artiste, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Morceau[]> rechMorceauxParArtisteAsync(String artiste)
    {
        return _iceI_rechMorceauxParArtisteAsync(artiste, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Morceau[]> rechMorceauxParArtisteAsync(String artiste, java.util.Map<String, String> context)
    {
        return _iceI_rechMorceauxParArtisteAsync(artiste, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Morceau[]> _iceI_rechMorceauxParArtisteAsync(String iceP_artiste, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Morceau[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "rechMorceauxParArtiste", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_artiste);
                 }, istr -> {
                     Morceau[] ret;
                     ret = listMorceauxHelper.read(istr);
                     istr.readPendingValues();
                     return ret;
                 });
        return f;
    }

    default Morceau[] rechMorceauxParGenre(String genre)
    {
        return rechMorceauxParGenre(genre, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Morceau[] rechMorceauxParGenre(String genre, java.util.Map<String, String> context)
    {
        return _iceI_rechMorceauxParGenreAsync(genre, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Morceau[]> rechMorceauxParGenreAsync(String genre)
    {
        return _iceI_rechMorceauxParGenreAsync(genre, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Morceau[]> rechMorceauxParGenreAsync(String genre, java.util.Map<String, String> context)
    {
        return _iceI_rechMorceauxParGenreAsync(genre, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Morceau[]> _iceI_rechMorceauxParGenreAsync(String iceP_genre, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Morceau[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "rechMorceauxParGenre", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_genre);
                 }, istr -> {
                     Morceau[] ret;
                     ret = listMorceauxHelper.read(istr);
                     istr.readPendingValues();
                     return ret;
                 });
        return f;
    }

    default boolean rechMorceauParTitre(String titre)
    {
        return rechMorceauParTitre(titre, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean rechMorceauParTitre(String titre, java.util.Map<String, String> context)
    {
        return _iceI_rechMorceauParTitreAsync(titre, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Boolean> rechMorceauParTitreAsync(String titre)
    {
        return _iceI_rechMorceauParTitreAsync(titre, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Boolean> rechMorceauParTitreAsync(String titre, java.util.Map<String, String> context)
    {
        return _iceI_rechMorceauParTitreAsync(titre, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Boolean> _iceI_rechMorceauParTitreAsync(String iceP_titre, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "rechMorceauParTitre", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_titre);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean rechMorceauParLocation(String location)
    {
        return rechMorceauParLocation(location, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean rechMorceauParLocation(String location, java.util.Map<String, String> context)
    {
        return _iceI_rechMorceauParLocationAsync(location, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Boolean> rechMorceauParLocationAsync(String location)
    {
        return _iceI_rechMorceauParLocationAsync(location, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Boolean> rechMorceauParLocationAsync(String location, java.util.Map<String, String> context)
    {
        return _iceI_rechMorceauParLocationAsync(location, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Boolean> _iceI_rechMorceauParLocationAsync(String iceP_location, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "rechMorceauParLocation", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_location);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default int supprimerMorceauxParArtiste(String artiste)
    {
        return supprimerMorceauxParArtiste(artiste, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int supprimerMorceauxParArtiste(String artiste, java.util.Map<String, String> context)
    {
        return _iceI_supprimerMorceauxParArtisteAsync(artiste, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Integer> supprimerMorceauxParArtisteAsync(String artiste)
    {
        return _iceI_supprimerMorceauxParArtisteAsync(artiste, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Integer> supprimerMorceauxParArtisteAsync(String artiste, java.util.Map<String, String> context)
    {
        return _iceI_supprimerMorceauxParArtisteAsync(artiste, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Integer> _iceI_supprimerMorceauxParArtisteAsync(String iceP_artiste, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "supprimerMorceauxParArtiste", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_artiste);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default int supprimerMorceauxParGenre(String genre)
    {
        return supprimerMorceauxParGenre(genre, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int supprimerMorceauxParGenre(String genre, java.util.Map<String, String> context)
    {
        return _iceI_supprimerMorceauxParGenreAsync(genre, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Integer> supprimerMorceauxParGenreAsync(String genre)
    {
        return _iceI_supprimerMorceauxParGenreAsync(genre, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Integer> supprimerMorceauxParGenreAsync(String genre, java.util.Map<String, String> context)
    {
        return _iceI_supprimerMorceauxParGenreAsync(genre, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Integer> _iceI_supprimerMorceauxParGenreAsync(String iceP_genre, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "supprimerMorceauxParGenre", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_genre);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default boolean supprimerMorceauParTitre(String titre)
    {
        return supprimerMorceauParTitre(titre, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean supprimerMorceauParTitre(String titre, java.util.Map<String, String> context)
    {
        return _iceI_supprimerMorceauParTitreAsync(titre, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Boolean> supprimerMorceauParTitreAsync(String titre)
    {
        return _iceI_supprimerMorceauParTitreAsync(titre, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Boolean> supprimerMorceauParTitreAsync(String titre, java.util.Map<String, String> context)
    {
        return _iceI_supprimerMorceauParTitreAsync(titre, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Boolean> _iceI_supprimerMorceauParTitreAsync(String iceP_titre, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "supprimerMorceauParTitre", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_titre);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default boolean supprimerMorceauParLocation(String location)
    {
        return supprimerMorceauParLocation(location, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default boolean supprimerMorceauParLocation(String location, java.util.Map<String, String> context)
    {
        return _iceI_supprimerMorceauParLocationAsync(location, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Boolean> supprimerMorceauParLocationAsync(String location)
    {
        return _iceI_supprimerMorceauParLocationAsync(location, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Boolean> supprimerMorceauParLocationAsync(String location, java.util.Map<String, String> context)
    {
        return _iceI_supprimerMorceauParLocationAsync(location, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Boolean> _iceI_supprimerMorceauParLocationAsync(String iceP_location, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Boolean> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "supprimerMorceauParLocation", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_location);
                 }, istr -> {
                     boolean ret;
                     ret = istr.readBool();
                     return ret;
                 });
        return f;
    }

    default int[] streamSound(String soundName, int duration)
    {
        return streamSound(soundName, duration, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int[] streamSound(String soundName, int duration, java.util.Map<String, String> context)
    {
        return _iceI_streamSoundAsync(soundName, duration, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<int[]> streamSoundAsync(String soundName, int duration)
    {
        return _iceI_streamSoundAsync(soundName, duration, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<int[]> streamSoundAsync(String soundName, int duration, java.util.Map<String, String> context)
    {
        return _iceI_streamSoundAsync(soundName, duration, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<int[]> _iceI_streamSoundAsync(String iceP_soundName, int iceP_duration, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<int[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "streamSound", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_soundName);
                     ostr.writeInt(iceP_duration);
                 }, istr -> {
                     int[] ret;
                     ret = istr.readIntSeq();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ManagerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ManagerPrx.class, _ManagerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ManagerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ManagerPrx.class, _ManagerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ManagerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ManagerPrx.class, _ManagerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ManagerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ManagerPrx.class, _ManagerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ManagerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ManagerPrx.class, _ManagerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ManagerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ManagerPrx.class, _ManagerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ManagerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ManagerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ManagerPrx ice_adapterId(String newAdapterId)
    {
        return (ManagerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ManagerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ManagerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ManagerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ManagerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ManagerPrx ice_invocationTimeout(int newTimeout)
    {
        return (ManagerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ManagerPrx ice_connectionCached(boolean newCache)
    {
        return (ManagerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ManagerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ManagerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ManagerPrx ice_secure(boolean b)
    {
        return (ManagerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ManagerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ManagerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ManagerPrx ice_preferSecure(boolean b)
    {
        return (ManagerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ManagerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ManagerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ManagerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ManagerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ManagerPrx ice_collocationOptimized(boolean b)
    {
        return (ManagerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ManagerPrx ice_twoway()
    {
        return (ManagerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ManagerPrx ice_oneway()
    {
        return (ManagerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ManagerPrx ice_batchOneway()
    {
        return (ManagerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ManagerPrx ice_datagram()
    {
        return (ManagerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ManagerPrx ice_batchDatagram()
    {
        return (ManagerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ManagerPrx ice_compress(boolean co)
    {
        return (ManagerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ManagerPrx ice_timeout(int t)
    {
        return (ManagerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ManagerPrx ice_connectionId(String connectionId)
    {
        return (ManagerPrx)_ice_connectionId(connectionId);
    }

    static String ice_staticId()
    {
        return "::Lecteurmp3::Manager";
    }
}
